[package]
name = "PredatorSnake_DQN"
version = "0.1.0"
edition = "2024"

[lib]
name = "predator_snake_dqn"
crate-type = ["cdylib", "rlib"]

[features]
default = []
gui = ["bevy/default"]

[dependencies]
bevy = { version = "0.14.2", default-features = false }
ndarray = "0.16.1"
numpy = "0.22.1"
pyo3 = { version = "0.22.6", features = ["extension-module"] }
rand = "0.8.5"
crossbeam-channel = "0.5"
